// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mls.Patients.Api.Data;

#nullable disable

namespace Mls.Patients.Api.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Patient.API.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "1 Brookside St",
                            DateNaissance = new DateOnly(1966, 12, 31),
                            Genre = "F",
                            Nom = "TestNone",
                            Prenom = "Test",
                            Telephone = "100-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "2 High St",
                            DateNaissance = new DateOnly(1945, 6, 24),
                            Genre = "M",
                            Nom = "TestBorderline",
                            Prenom = "Test",
                            Telephone = "200-333-4444"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "3 Club Road",
                            DateNaissance = new DateOnly(2004, 6, 18),
                            Genre = "M",
                            Nom = "TestInDanger",
                            Prenom = "Test",
                            Telephone = "300-444-5555"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "4 Valley Dr",
                            DateNaissance = new DateOnly(2002, 6, 28),
                            Genre = "F",
                            Nom = "TestEarlyOnse",
                            Prenom = "Test",
                            Telephone = "400-555-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
